# Generated by Django 3.2 on 2021-05-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_sale', models.IntegerField(max_length=10000)),
                ('net_change', models.IntegerField(max_length=10000)),
                ('percentage_change', models.IntegerField(max_length=10000)),
                ('country', models.CharField(max_length=1000)),
                ('industry', models.CharField(max_length=10000)),
            ],
        ),
    ]
