# Generated by Django 3.2 on 2021-05-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='last_sale',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='net_change',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='percentage_change',
            field=models.IntegerField(),
        ),
    ]
