# Generated by Django 3.2 on 2021-05-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0003_auto_20210513_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='last_sale',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='net_change',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='percentage_change',
            field=models.FloatField(),
        ),
    ]
