# Generated by Django 3.2 on 2021-05-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0004_auto_20210513_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='username',
        ),
    ]
