# Generated by Django 3.2 on 2021-06-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0005_rename_email_signup_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='datacsv',
        ),
    ]
