# Generated by Django 3.2 on 2021-06-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0006_rename_data_datacsv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacsv',
            name='percentage_change',
        ),
    ]
